# 100 numpy exercises

Source: https://github.com/rougier/numpy-100


In [2]:
!pip install numpy --upgrade

     |████████████████████████████████| 14.5 MB 3.3 MB/s eta 0:00:01


In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [12]:
myVector = np.zeros(10)
myVector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [13]:
print('The size of this array is %d bytes' % (myVector.size * myVector.itemsize))

The size of this array is 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
nullVector = np.zeros(10)
nullVector[4] = 1
nullVector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
myVector = np.arange(10, 50)
myVector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
reversedVector = np.flip(myVector)
reversedVector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [27]:
myMatrix = np.arange(0, 9)
newMatrix = myMatrix.reshape(3,3)
newMatrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [30]:
myVector = np.array([1,2,0,0,4,0])
print(np.nonzero(myVector))

(array([0, 1, 4]),)


Save your progress by commiting your work to Jovian

#### 11. Create a 3x3 identity matrix (★☆☆)

In [33]:
idMatrix = np.identity(3)
idMatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [41]:
myArray = np.random.rand(3,3,3)
myArray

array([[[0.96636693, 0.3659155 , 0.21409123],
        [0.37295262, 0.51658811, 0.7885149 ],
        [0.99963053, 0.4337101 , 0.99584115]],

       [[0.60365327, 0.28609323, 0.54317677],
        [0.45162332, 0.25222726, 0.91755335],
        [0.11847795, 0.62789405, 0.67497515]],

       [[0.98302707, 0.45431667, 0.72727112],
        [0.37978636, 0.74388279, 0.83357091],
        [0.01243106, 0.24983485, 0.23757432]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [53]:
randMatrix = np.random.rand(10,10)
print(randMatrix)
print("Max value: {}, Min value: {}".format(np.max(randMatrix), np.min(randMatrix)))

[[0.49769317 0.07179089 0.32765145 0.48921064 0.44922429 0.207234
  0.8782505  0.03348632 0.29554151 0.08845734]
 [0.1225427  0.56655158 0.72531162 0.75770796 0.6169392  0.0558032
  0.42303923 0.23117496 0.81709834 0.34972331]
 [0.0758986  0.22623888 0.57968324 0.0389867  0.68848198 0.86195658
  0.41528482 0.68956736 0.34772707 0.74629055]
 [0.35967244 0.73759214 0.23617704 0.72971075 0.80894351 0.38220295
  0.60675886 0.73463344 0.45390371 0.86023926]
 [0.72234203 0.68787295 0.41208201 0.35689879 0.38260498 0.05155911
  0.29691466 0.5187096  0.30316294 0.31195437]
 [0.9455153  0.41896757 0.22322388 0.70041318 0.62839766 0.88748584
  0.2559306  0.89623512 0.01602313 0.00341951]
 [0.33412662 0.24877759 0.18195754 0.03803235 0.17141875 0.05825161
  0.84687317 0.67106281 0.78268882 0.03447199]
 [0.0360234  0.57671277 0.37438166 0.12677878 0.72237364 0.24683182
  0.88442422 0.36938382 0.86639197 0.72061636]
 [0.81266608 0.42468484 0.97137547 0.56602603 0.34905592 0.12393884
  0.09728371 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [58]:
myVector = np.random.rand(30)
print(myVector)
print("The mean value is {}".format(np.mean(myVector)))

[0.90492383 0.25669719 0.12780938 0.14499247 0.12440945 0.85789481
 0.76405244 0.08681462 0.16880563 0.11581186 0.51953444 0.45638603
 0.59571418 0.15746086 0.83158543 0.0150341  0.80224841 0.14561526
 0.84271286 0.56249951 0.767846   0.60946107 0.49931253 0.50128101
 0.3706104  0.44272511 0.15148212 0.88230526 0.99068472 0.24994751]
The mean value is 0.46488861685749044


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [7]:
import numpy as np

x = np.ones(shape=(5,5))

x[1:-1, 1:-1] = 0

print(x)

#for problem 16
arr = x

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [8]:
def addBorder(arr):
    return np.pad(arr, 1)

addBorder(arr)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [10]:
x = np.diag(1+np.arange(4), k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [13]:
eights = np.zeros(shape=(8,8), dtype=int)
eights[::2, 1::2] = 1
eights[1::2, ::2] = 1

print(eights)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [15]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


Save your progress by commiting your work to Jovian

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
myTile = np.array([[0,1], [1,0]])

myEight = np.tile(myTile, (4,4))

print(myEight)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [25]:
import numpy.linalg as LA

rMat = np.random.random((5,5))

print(rMat)

rMat = (rMat - np.mean(rMat)) / (np.std(rMat))

print(rMat)

[[0.28629615 0.32588474 0.33905593 0.09752058 0.5134329 ]
 [0.98636792 0.01959391 0.32515664 0.81551492 0.12190374]
 [0.43688647 0.55052689 0.36551945 0.74013576 0.61282404]
 [0.32844279 0.81949889 0.00552883 0.36574148 0.97449531]
 [0.6558538  0.73991439 0.61868979 0.15393208 0.1867121 ]]
[[-0.60051531 -0.45994408 -0.41317577 -1.27082001  0.20600233]
 [ 1.88530102 -1.54752217 -0.46252941  1.27863582 -1.18424023]
 [-0.06579889  0.33771577 -0.31920904  1.01097934  0.55892061]
 [-0.45086094  1.29278212 -1.59746449 -0.31842067  1.8431437 ]
 [ 0.71171077  1.01019331  0.57974872 -1.07051393 -0.95411857]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [32]:
import numpy as np

color = np.dtype([('r', np.ubyte, (1,)), ('g', np.ubyte, (1,)), ('b', np.ubyte, (1,)), ('a', np.ubyte, (1,))])

colors = np.zeros((5,5), dtype=color)

print(colors)

[[([0], [0], [0], [0]) ([0], [0], [0], [0]) ([0], [0], [0], [0])
  ([0], [0], [0], [0]) ([0], [0], [0], [0])]
 [([0], [0], [0], [0]) ([0], [0], [0], [0]) ([0], [0], [0], [0])
  ([0], [0], [0], [0]) ([0], [0], [0], [0])]
 [([0], [0], [0], [0]) ([0], [0], [0], [0]) ([0], [0], [0], [0])
  ([0], [0], [0], [0]) ([0], [0], [0], [0])]
 [([0], [0], [0], [0]) ([0], [0], [0], [0]) ([0], [0], [0], [0])
  ([0], [0], [0], [0]) ([0], [0], [0], [0])]
 [([0], [0], [0], [0]) ([0], [0], [0], [0]) ([0], [0], [0], [0])
  ([0], [0], [0], [0]) ([0], [0], [0], [0])]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [33]:
five_three = np.array(np.random.randint(20, size=(5,3)))
three_two = np.array(np.random.randint(20, size=(3,2)))
print("MATRIX A\n{}".format(five_three))
print("MATRIX B\n{}".format(three_two))
print("MATRIX AB\n{}".format(five_three @ three_two))
print(np.dot(five_three, three_two))

MATRIX A
[[ 0 13 13]
 [ 6  9 13]
 [ 8 10  8]
 [ 4 15  1]
 [ 1  0  0]]
MATRIX B
[[14  1]
 [10  3]
 [ 5 18]]
MATRIX AB
[[195 273]
 [239 267]
 [252 182]
 [211  67]
 [ 14   1]]
[[195 273]
 [239 267]
 [252 182]
 [211  67]
 [ 14   1]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [37]:
#values between 3 and 8
y = np.random.randint(10, size=(10))

print(y)

y[(3 < y) & (y < 8)] *= -1

print(y)

#indices between 3 and 8
z = np.arange(10)
print(z)
z[(3 < z) & (z < 8)] *= -1
print(z)

[0 2 6 4 8 3 6 3 2 0]
[ 0  2 -6 -4  8  3 -6  3  2  0]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [135]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [152]:
Z = np.array([1,2,3,4,5,6,7,8,9,10])
print("Z**Z is VALID: {}".format(Z**Z))
print("2 << Z >> 2 is VALID: {}".format(2 << Z >> 2))
print("Z <- Z is VALID: {}".format(Z <- Z))
print("1j*Z is VALID: {}".format(1j*Z))
print("Z/1/1 is VALID: {}".format(Z/1/1))
print("Z<Z>Z is NOT VALID: {}".format(Z<Z>Z))

Z**Z is VALID: [          1           4          27         256        3125       46656
      823543    16777216   387420489 10000000000]
2 << Z >> 2 is VALID: [  1   2   4   8  16  32  64 128 256 512]
Z <- Z is VALID: [False False False False False False False False False False]
1j*Z is VALID: [0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j 0. +9.j
 0.+10.j]
Z/1/1 is VALID: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [42]:
np.array(0) / np.array(0)

<ipython-input-42-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [43]:
np.array(0) // np.array(0)

<ipython-input-43-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [44]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [47]:
x = np.random.uniform(-15., 15., 10)
print(x)
print()
y = x * 0.5
print(y)
print()
print(np.copysign(np.ceil(np.abs(y)), y))

[-5.2899576  -0.06188037  6.19579038  8.78832062 -8.24763068  4.1465638
 -7.2718523   9.40588593 -0.362206    8.00806744]

[-2.6449788  -0.03094019  3.09789519  4.39416031 -4.12381534  2.0732819
 -3.63592615  4.70294297 -0.181103    4.00403372]

[-3. -1.  4.  5. -5.  3. -4.  5. -1.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
x = np.arange(100)
y = np.arange(55,150)

print(np.intersect1d(x,y))

[55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78
 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


Save your progress by commiting your work to Jovian

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [49]:
#import numpy as np
#from numpy import *
#print(np.seterr(all=None, divide=None, over=None, under=None, invalid=None))
#print(np.geterr())

defaults = np.seterr(all='ignore')
x = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [13]:
from numpy.lib import scimath
np.sqrt(-1)

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


nan

In [14]:
emath.sqrt([-1])

array([0.+1.j])

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [15]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday's date was: ", yesterday)
today = np.datetime64('today', 'D')
print("Today's date is: ", today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's date is: ", tomorrow)

Yesterday's date was:  2020-08-31
Today's date is:  2020-09-01
Tomorrow's date is:  2020-09-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [21]:
for i in range(31):
    target_date = np.datetime64('2016-07', 'D') + np.timedelta64(i, 'D')
    print("Date of day {} from July 2016: ".format(i+1), target_date)

Date of day 1 from July 2016:  2016-07-01
Date of day 2 from July 2016:  2016-07-02
Date of day 3 from July 2016:  2016-07-03
Date of day 4 from July 2016:  2016-07-04
Date of day 5 from July 2016:  2016-07-05
Date of day 6 from July 2016:  2016-07-06
Date of day 7 from July 2016:  2016-07-07
Date of day 8 from July 2016:  2016-07-08
Date of day 9 from July 2016:  2016-07-09
Date of day 10 from July 2016:  2016-07-10
Date of day 11 from July 2016:  2016-07-11
Date of day 12 from July 2016:  2016-07-12
Date of day 13 from July 2016:  2016-07-13
Date of day 14 from July 2016:  2016-07-14
Date of day 15 from July 2016:  2016-07-15
Date of day 16 from July 2016:  2016-07-16
Date of day 17 from July 2016:  2016-07-17
Date of day 18 from July 2016:  2016-07-18
Date of day 19 from July 2016:  2016-07-19
Date of day 20 from July 2016:  2016-07-20
Date of day 21 from July 2016:  2016-07-21
Date of day 22 from July 2016:  2016-07-22
Date of day 23 from July 2016:  2016-07-23
Date of day 24 from 

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [26]:
A = np.array(np.random.randint(100, size=(5,5)))
B = np.array(np.random.randint(100, size=(5,5)))

print(A)
print(B)

print((A+B)*(-A/2))

[[17 71 40 35 96]
 [51 41 31 43 32]
 [76  5 80 51 56]
 [55 74 90 94 50]
 [44 78 56 79 56]]
[[51 53 68 57 50]
 [24  3 13  0 40]
 [52 75 39 97 98]
 [ 4 29 90 84 83]
 [67 82 56  2  0]]
[[ -578.  -4402.  -2160.  -1610.  -7008. ]
 [-1912.5  -902.   -682.   -924.5 -1152. ]
 [-4864.   -200.  -4760.  -3774.  -4312. ]
 [-1622.5 -3811.  -8100.  -8366.  -3325. ]
 [-2442.  -6240.  -3136.  -3199.5 -1568. ]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [19]:
x = np.random.uniform(1., 20., 10)
print(x)
print(np.floor(x))
print(np.trunc(x))
print(x.astype(int))
print(x - x % 1)

[ 7.01735544  2.25259161  5.91661594 17.9247397  17.21233129  1.2568261
 15.64955743  8.6334055  17.76246444 17.76267701]
[ 7.  2.  5. 17. 17.  1. 15.  8. 17. 17.]
[ 7.  2.  5. 17. 17.  1. 15.  8. 17. 17.]
[ 7  2  5 17 17  1 15  8 17 17]
[ 7.  2.  5. 17. 17.  1. 15.  8. 17. 17.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [30]:
x = np.random.randint(5, size=(5,5))
print(x)

print()

y = np.zeros((5,5))

for i in range(5):
    y[i] = np.arange(5)
    
print()

print(y)

[[4 4 2 0 0]
 [3 4 2 4 2]
 [4 3 1 3 4]
 [2 0 0 1 1]
 [1 0 4 3 2]]


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [4]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(), dtype=float, count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [6]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

Save your progress by commiting your work to Jovian

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

Save and commit your work.

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

Save and commit your work.

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)